use schema1;

DROP TABLE USER;

create table USER(
    ID INT NOT NULL primary key,
    NAME VARCHAR(32) NOT NULL,
    PASSWORD VARCHAR(32) NOT NULL,
    AUTHORITY_TYPE VARCHAR(32) NOT NULL,
    CREATE_TIME DATETIME,
    CREATE_NAME VARCHAR(32),
    UPDATE_TIME DATETIME,
    UPDATE_NAME VARCHAR(32)
);